#!/bin/zsh
# launchd entry point for every nightly job. The plists are generated by `python -m wt.ops.agents` from
# wt.ops.schedule; locking, preflight, waiting, deadlines, alerts and heartbeats live in wt.ops.jobs.
# Usage: deploy/run_job.sh <routine|paper-b|forward|weekly> [--preflight-only]
ROOT="${0:A:h:h}"
cd "$ROOT" || exit 1
export PYTHONPATH=src PYTHONDONTWRITEBYTECODE=1
exec /usr/bin/caffeinate -is .venv/bin/python -m wt.ops.jobs run "$@"
