// Regenerates src/lib/snapshot.types.ts from src/lib/snapshot.schema.json (the Python-owned contract).
// Run with `pnpm gen:types` after `make schema` changes the schema. The output is committed.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = join(root, "src/lib/snapshot.schema.json");
const outPath = join(root, "src/lib/snapshot.types.ts");

const schema = JSON.parse(readFileSync(schemaPath, "utf8"));
// Name the root type `Snapshot` instead of deriving it from the long schema title.
delete schema.title;
delete schema.$id;

const ts = await compile(schema, "Snapshot", {
  bannerComment:
    "/* Generated by `pnpm gen:types` from snapshot.schema.json. Do not edit by hand. */",
  additionalProperties: false,
  strictIndexSignatures: true,
  unreachableDefinitions: false,
  format: true,
  style: { semi: true, singleQuote: false, printWidth: 100 },
});

writeFileSync(outPath, ts);
console.log(`wrote ${outPath}`);
