"""Write dashboard/src/lib/thresholds.gen.ts from wt.ops.thresholds (run by `make schema`)."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from wt.ops.thresholds import PUBLIC  # noqa: E402

OUT = ROOT / "dashboard" / "src" / "lib" / "thresholds.gen.ts"


def render() -> str:
    lines = ["// Generated by scripts/gen_thresholds_ts.py from src/wt/ops/thresholds.py. Do not edit by hand.", ""]
    lines += [f"export const {k} = {v!r};" for k, v in sorted(PUBLIC.items())]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(ROOT)}")
