/* Generated by `pnpm gen:types` from crypto.schema.json. Do not edit by hand. */

export interface CryptoSnapshot {
  schema: string | null;
  schema_version: number | null;
  run_id: string | null;
  as_of: string | null;
  redaction?: string | null;
  withheld?: number | null;
  truncated?: number | null;
  /**
   * @maxItems 2000
   */
  expected_windows?:
    | ({
        session?: string | null;
        start?: string | null;
        end?: string | null;
      } | null)[]
    | null;
  config?: {
    hash?: string | null;
    venue?: string | null;
    quote_currency?: string | null;
    timeframe_min?: number | null;
    /**
     * @maxItems 2000
     */
    pairs?: (string | null)[] | null;
  } | null;
  strategy?: {
    name?: string | null;
    rsi_period?: number | null;
    rsi_below?: number | null;
    ema_period?: number | null;
    stop_loss_pct?: number | null;
    take_profit_pct?: number | null;
    time_stop_bars?: number | null;
    taker_fee_pct?: number | null;
    slippage_bps?: number | null;
    net_win_pct?: number | null;
    net_loss_pct?: number | null;
    breakeven_win_rate?: number | null;
  } | null;
  /**
   * @maxItems 2000
   */
  market?:
    | ({
        pair?: string | null;
        bar?: string | null;
        close?: number | null;
        rsi?: number | null;
        vwap_distance_pct?: number | null;
        ema8_distance_pct?: number | null;
        atr_pct?: number | null;
        volume_ratio?: number | null;
        would_fire?: boolean | null;
        /**
         * @maxItems 2000
         */
        why_not?: (string | null)[] | null;
        tradable?: boolean | null;
        /**
         * @maxItems 2000
         */
        quality?: (string | null)[] | null;
        spread_pct?: number | null;
      } | null)[]
    | null;
  quality?: {
    days?: number | null;
    min_days?: number | null;
    min_traded_share?: number | null;
    max_median_spread_pct?: number | null;
    /**
     * @maxItems 2000
     */
    pairs?:
      | ({
          pair?: string | null;
          bars?: number | null;
          traded_share?: number | null;
          median_spread_pct?: number | null;
          p95_spread_pct?: number | null;
          passes?: boolean | null;
        } | null)[]
      | null;
  } | null;
  book?: {
    equity?: number | null;
    cash?: number | null;
    exposure?: number | null;
    start_equity?: number | null;
    return_pct?: number | null;
    /**
     * @maxItems 2000
     */
    positions?:
      | ({
          pair?: string | null;
          qty?: number | null;
          entry_price?: number | null;
          stop?: number | null;
          target?: number | null;
          entry_time?: string | null;
          mark?: number | null;
          unrealised_pct?: number | null;
        } | null)[]
      | null;
  } | null;
  risk?: {
    limits?: {
      max_notional?: number | null;
      max_open_exposure?: number | null;
      max_entries_per_day?: number | null;
      max_orders_per_day?: number | null;
      daily_loss_latch?: number | null;
    } | null;
    today?: {
      day?: string | null;
      entries?: number | null;
      orders?: number | null;
      realised?: number | null;
    } | null;
    latched?: boolean | null;
    chain_ok?: boolean | null;
  } | null;
  kill?: {
    on?: boolean | null;
    since?: string | null;
  } | null;
  perf?: {
    trades?: number | null;
    wins?: number | null;
    losses?: number | null;
    win_rate?: number | null;
    mean_r?: number | null;
    total_r?: number | null;
    total_pnl?: number | null;
    fees?: number | null;
    by_reason?: {
      [k: string]: number | null | undefined;
    } | null;
    by_pair?: {
      [k: string]:
        | {
            trades?: number | null;
            mean_r?: number | null;
            pnl?: number | null;
          }
        | null
        | undefined;
    } | null;
    /**
     * @maxItems 2000
     */
    equity_curve?:
      | ({
          t?: string | null;
          equity?: number | null;
        } | null)[]
      | null;
    /**
     * @maxItems 2000
     */
    recent?:
      | ({
          t?: string | null;
          pair?: string | null;
          reason?: string | null;
          r?: number | null;
          pnl?: number | null;
          held_min?: number | null;
        } | null)[]
      | null;
  } | null;
  activity?: {
    cycles_24h?: number | null;
    expected_24h?: number | null;
    failed_24h?: number | null;
    observations_7d?: number | null;
    fires_7d?: number | null;
    entries_7d?: number | null;
    refused_7d?: {
      [k: string]: number | null | undefined;
    } | null;
    /**
     * @maxItems 2000
     */
    daily?:
      | ({
          day?: string | null;
          observations?: number | null;
          fires?: number | null;
          entries?: number | null;
          exits?: number | null;
          cycles?: number | null;
        } | null)[]
      | null;
  } | null;
  distributions?: {
    /**
     * @maxItems 2000
     */
    [k: string]:
      | ({
          lo?: number | null;
          hi?: number | null;
          n?: number | null;
        } | null)[]
      | null
      | undefined;
  } | null;
  ml?: {
    observations?: number | null;
    labelled?: number | null;
    model?: string | null;
    status?: string | null;
  } | null;
  jobs?: {
    last?: {
      [k: string]:
        | {
            status?: string | null;
            exit?: number | null;
            started?: string | null;
            ended?: string | null;
            sha?: string | null;
          }
        | null
        | undefined;
    } | null;
    /**
     * @maxItems 2000
     */
    runs?:
      | ({
          job?: string | null;
          status?: string | null;
          exit?: number | null;
          started?: string | null;
          ended?: string | null;
          sha?: string | null;
        } | null)[]
      | null;
  } | null;
  alerts?: {
    /**
     * @maxItems 2000
     */
    firing?:
      | ({
          key?: string | null;
          since?: string | null;
        } | null)[]
      | null;
  } | null;
}
