/* Generated by `pnpm gen:types` from hft.schema.json. Do not edit by hand. */

export interface HftSnapshot {
  schema: "hft-lab/snapshot";
  schema_version: 1;
  run_id: string;
  /**
   * The moment this snapshot describes, ISO 8601 in UTC. The dashboard orders snapshots by it and measures freshness from it.
   */
  as_of: string;
  /**
   * When the snapshot was built, ISO 8601 in UTC.
   */
  generated_at: string;
  /**
   * Short commit id of the publishing code.
   */
  version: string | null;
  /**
   * When the desk expects to publish. Silence inside a window pages; silence outside one does not. Always list the window that is open or the next one to open: once every listed window has ended, the dashboard assumes US equity weekday hours.
   *
   * @maxItems 32
   */
  expected_windows: {
    session: string;
    start: string;
    end: string;
  }[];
  desk: {
    mode: "paper";
    stage: "foundation" | "recording" | "shadow" | "paper";
    venue: "ibkr_paper" | "sim";
    market_open: boolean;
    kill: boolean;
    flatten: boolean;
  };
  /**
   * @maxItems 8
   */
  phases: {
    id: "F0" | "F1" | "F2" | "F3" | "F4" | "F5" | "F6" | "F7";
    state: "done" | "open" | "not_started";
  }[];
  health: {
    level: "ok" | "warn" | "bad";
    /**
     * @maxItems 20
     */
    reasons: string[];
  };
  recorder?: {
    state: "running" | "stopped" | "never";
    events_today: number;
    last_event_at: string | null;
    gaps_unexplained_today: number;
    disk_used_mb: number | null;
  } | null;
  /**
   * @maxItems 40
   */
  pairs?:
    | {
        pair: string;
        form: "cash" | "cfd";
        last_quote_at: string | null;
        updates_per_second: number | null;
        /**
         * In the unit named by spread_unit.
         */
        spread_median: number | null;
        spread_unit: "price_units";
      }[]
    | null;
  /**
   * @maxItems 20
   */
  sleeves?:
    | {
        name: "control" | "directional_change" | "ml" | "dl";
        stage: "shadow" | "min_size" | "normal" | "stepped_down" | "off";
        trades_today: number;
        trades_total: number;
        /**
         * Null when it has not been worked out.
         */
        net_today: number | null;
        /**
         * Null when it has not been worked out.
         */
        net_total: number | null;
        /**
         * The currency of this sleeve's net results.
         */
        currency: string;
      }[]
    | null;
  books?: {
    /**
     * The desk's own conservative book. It is the result of record.
     */
    shadow: {
      /**
       * Null when it has not been worked out.
       */
      net_today: number | null;
      /**
       * Null when it has not been worked out.
       */
      net_total: number | null;
    };
    /**
     * The broker's own book.
     */
    broker: {
      /**
       * Null when it has not been worked out.
       */
      net_today: number | null;
      /**
       * Null when it has not been worked out.
       */
      net_total: number | null;
    };
    /**
     * The currency of both books' net results.
     */
    currency: string;
    reconciliation_breaks_today: number;
    open_positions: number;
  } | null;
  learning?: {
    champion: string | null;
    challengers: number;
    last_training_at: string | null;
    last_promotion_at: string | null;
    last_rollback_at: string | null;
  } | null;
}
