/* Generated by `pnpm gen:types` from options-live.schema.json. Do not edit by hand. */

/**
 * What the Options desk needs between editions: the open option positions of the paper account kept for manual option trades, and open interest by strike for the desk's names. Paper only: a document that does not say so is refused. No account number, no balances, no buying power.
 */
export interface OptionsLive {
  schema: "stocksdelta/options-live";
  schema_version?: number | null;
  run_id: string;
  as_of: string;
  /**
   * Always true. The publisher reads a paper account and nothing else.
   */
  paper: true;
  market?: {
    is_open?: boolean | null;
    next_open?: string | null;
    next_close?: string | null;
  } | null;
  /**
   * Open option positions, one row per contract. Stock positions are not sent.
   *
   * @maxItems 100
   */
  positions: {
    /**
     * The OCC symbol: root, yymmdd, C or P, strike in thousandths.
     */
    contract: string;
    /**
     * Contracts held. Negative is short.
     */
    qty: number;
    /**
     * Average price paid per share.
     */
    avg_price?: number | null;
    /**
     * The broker's current mark per share.
     */
    price?: number | null;
    market_value?: number | null;
    unrealized_pl?: number | null;
  }[];
  /**
   * Open interest by contract for the desk's names, as the exchange last reported it (one session behind).
   *
   * @maxItems 60
   */
  open_interest?:
    | {
        symbol: string;
        as_of?: string | null;
        /**
         * @maxItems 600
         */
        rows: {
          expiry: string;
          strike: number;
          kind: "call" | "put";
          oi: number;
        }[];
      }[]
    | null;
  /**
   * @maxItems 24
   */
  problems?: string[] | null;
}
