/* Generated by `pnpm gen:types` from options.schema.json. Do not edit by hand. */

export interface OptionsEdition {
  schema: "stocksdelta/options";
  schema_version?: number | null;
  run_id?: string | null;
  as_of?: string | null;
  session: string;
  built_from?: string | null;
  source?: string | null;
  /**
   * @maxItems 60
   */
  tickers: {
    symbol: string;
    from_bar?: string | null;
    half_day?: boolean | null;
    last?: {
      open?: number | null;
      high: number;
      low: number;
      close: number;
    } | null;
    atr14?: number | null;
    close_strength?: {
      pos?: number | null;
      chip?: "STRONG" | "MID" | "WEAK" | null;
    } | null;
    expected_move?: {
      annual_iv?: number | null;
      iv_pct_52w?: number | null;
      day?: number | null;
      week?: number | null;
      from?: string | null;
    } | null;
    /**
     * @maxItems 40
     */
    levels?: {
      name: string;
      price: number;
      tf?: "day" | "week" | "month" | "52w" | "ma" | "sd" | null;
      weight?: number | null;
      lo?: number | null;
      hi?: number | null;
    }[];
    /**
     * @maxItems 40
     */
    zones?: {
      lo: number;
      hi: number;
      weight?: number | null;
      /**
       * @maxItems 24
       */
      members?: string[];
      side: "support" | "resistance";
      big?: boolean | null;
    }[];
    /**
     * Recent daily bars, oldest first, for the level map.
     *
     * @maxItems 60
     */
    bars?: {
      d: string;
      o: number;
      h: number;
      l: number;
      c: number;
    }[];
    /**
     * @maxItems 24
     */
    problems?: string[];
    /**
     * How the name's options are priced against its own past and its own movement. Volatilities are annualised fractions (0.24 is 24%), as expected_move.annual_iv is. New in version 2.
     */
    vol?: {
      /**
       * 30-day implied vol as a fraction. The ceiling of 5 refuses a value sent as a percentage.
       */
      iv30?: number | null;
      /**
       * The day's change in iv30 as a fraction: 0.012 is 1.2 volatility points. The bounds refuse a value sent in points.
       */
      iv_change_1d?: number | null;
      /**
       * Where iv30 sits in its own last 13 weeks, as a fraction.
       */
      iv_pct_13w?: number | null;
      /**
       * Where iv30 sits in its own last 26 weeks, as a fraction. The 52-week figure is expected_move.iv_pct_52w.
       */
      iv_pct_26w?: number | null;
      /**
       * 30-day realised vol as a fraction.
       */
      hv30?: number | null;
      opt_volume?: number | null;
      opt_volume_avg20?: number | null;
    } | null;
  }[];
  /**
   * @maxItems 24
   */
  rules?: {
    id: string;
    label?: string | null;
    side?: "call" | "put" | null;
    status: "proven" | "probation" | "retired";
    since?: string | null;
    backtest?: {
      n?: number | null;
      avg_r?: number | null;
      ci_lo?: number | null;
      ci_hi?: number | null;
      period?: string | null;
    } | null;
    live?: {
      n?: number | null;
      avg_r?: number | null;
      wins?: number | null;
    } | null;
  }[];
  /**
   * @maxItems 60
   */
  paper?: {
    session: string;
    symbol: string;
    rule: string;
    side?: "call" | "put" | null;
    entry?: number | null;
    stop?: number | null;
    target?: number | null;
    exit?: "target" | "stop" | "close" | null;
    r?: number | null;
  }[];
  expected_move_check?: {
    inside_1d_pct?: number | null;
    touch_5d_pct?: number | null;
    n?: number | null;
    period?: string | null;
  } | null;
  /**
   * The day itself, as of the close the edition was built from. New in version 2.
   */
  market?: {
    vix?: {
      close?: number | null;
      change?: number | null;
      /**
       * A fraction: 0.34 is the 34th percentile of the last year.
       */
      pct_52w?: number | null;
    } | null;
    /**
     * Whether the session the levels are for closes early. The site works the hours out from this alone.
     */
    session?: {
      half_day?: boolean | null;
    } | null;
    /**
     * Whether the macro rows in `events` are the whole calendar for the session and the week after it. Only 'complete' lets the page say a day has no scheduled release.
     */
    calendar?: "complete" | "partial" | null;
  } | null;
  /**
   * Scheduled events near the session: macro releases (no symbol) and earnings (one symbol). Codes only, never headlines: the site names the codes it knows and shows any other as 'Other release'. New in version 2.
   *
   * @maxItems 400
   */
  events?:
    | {
        date: string;
        /**
         * New York time, 8:30 or 08:30, seconds allowed and ignored.
         */
        time_et?: string | null;
        kind: "macro" | "earnings";
        /**
         * A code such as cpi or fomc_decision. Never drawn as written.
         */
        type: string;
        severity?: "high" | "medium" | "low" | null;
        symbol?: string | null;
        /**
         * For earnings: bmo, amc or during. Another code is accepted and not drawn.
         */
        when?: string | null;
      }[]
    | null;
}
