/* Generated by `pnpm gen:types` from options.schema.json. Do not edit by hand. */

export interface OptionsEdition {
  schema: "stocksdelta/options";
  schema_version?: number | null;
  run_id?: string | null;
  as_of?: string | null;
  session: string;
  built_from?: string | null;
  source?: string | null;
  /**
   * @maxItems 60
   */
  tickers: {
    symbol: string;
    from_bar?: string | null;
    half_day?: boolean | null;
    last?: {
      open?: number | null;
      high: number;
      low: number;
      close: number;
    } | null;
    atr14?: number | null;
    close_strength?: {
      pos?: number | null;
      chip?: "STRONG" | "MID" | "WEAK" | null;
    } | null;
    expected_move?: {
      annual_iv?: number | null;
      iv_pct_52w?: number | null;
      day?: number | null;
      week?: number | null;
      from?: string | null;
    } | null;
    /**
     * @maxItems 40
     */
    levels?: {
      name: string;
      price: number;
      tf?: "day" | "week" | "month" | "52w" | "ma" | "sd" | null;
      weight?: number | null;
      lo?: number | null;
      hi?: number | null;
    }[];
    /**
     * @maxItems 40
     */
    zones?: {
      lo: number;
      hi: number;
      weight?: number | null;
      /**
       * @maxItems 24
       */
      members?: string[];
      side: "support" | "resistance";
      big?: boolean | null;
    }[];
    /**
     * @maxItems 24
     */
    problems?: string[];
  }[];
  /**
   * @maxItems 24
   */
  rules?: {
    id: string;
    label?: string | null;
    side?: "call" | "put" | null;
    status: "proven" | "probation" | "retired";
    since?: string | null;
    backtest?: {
      n?: number | null;
      avg_r?: number | null;
      ci_lo?: number | null;
      ci_hi?: number | null;
      period?: string | null;
    } | null;
    live?: {
      n?: number | null;
      avg_r?: number | null;
      wins?: number | null;
    } | null;
  }[];
  /**
   * @maxItems 60
   */
  paper?: {
    session: string;
    symbol: string;
    rule: string;
    side?: "call" | "put" | null;
    entry?: number | null;
    stop?: number | null;
    target?: number | null;
    exit?: "target" | "stop" | "close" | null;
    r?: number | null;
  }[];
  expected_move_check?: {
    inside_1d_pct?: number | null;
    touch_5d_pct?: number | null;
    n?: number | null;
    period?: string | null;
  } | null;
}
