/* Generated by `pnpm gen:types` from radar.schema.json. Do not edit by hand. */

export interface RadarEdition {
  schema: "stocksdelta/radar";
  schema_version?: number | null;
  run_id: string | null;
  as_of: string | null;
  edition_date: string;
  title?: string | null;
  prices_as_of?: string | null;
  report_url?: string | null;
  summary?: string | null;
  regime?: string | null;
  footnote?: string | null;
  lists?:
    | {
        name: string;
        ibkr_id?: string | null;
        note?: string | null;
        symbols?: string[] | null;
      }[]
    | null;
  tickers?:
    | {
        symbol: string;
        company?: string | null;
        price?: number | null;
        change_pct?: number | null;
        support?: number | null;
        support_2?: number | null;
        resistance?: number | null;
        high_52w?: number | null;
        to_support_pct?: number | null;
        to_resistance_pct?: number | null;
        off_high_pct?: number | null;
        ma10?: number | null;
        ma20?: number | null;
        ma40?: number | null;
        rs13?: number | null;
        rs26?: number | null;
        volume_ratio?: number | null;
        above_mas?: number | null;
        stance?: string | null;
        tag?: "new" | "risk" | null;
        lists?: string[] | null;
        why?: string | null;
        notes?:
          | {
              label?: string | null;
              text?: string | null;
              source?: string | null;
              date?: string | null;
              confidence?: "High" | "Medium" | "Low" | null;
            }[]
          | null;
      }[]
    | null;
  avoid?:
    | {
        symbols?: string | null;
        price?: string | null;
        why?: string | null;
      }[]
    | null;
}
