/* Generated by `pnpm gen:types` from snapshot.schema.json. Do not edit by hand. */

export interface Snapshot {
  schema: string | null;
  schema_version: number | null;
  run_id: string | null;
  as_of: string | null;
  redaction?: string | null;
  withheld?: number | null;
  truncated?: number | null;
  collector?: {
    sha?: string | null;
    branch?: string | null;
    dirty?: boolean | null;
    exit_code?: number | null;
    fresh_sources?: number | null;
    total_sources?: number | null;
    duration_s?: number | null;
    sources?: {
      [k: string]:
        | {
            ok?: boolean | null;
            stale?: boolean | null;
            as_of?: string | null;
            error?: string | null;
            ms?: number | null;
          }
        | null
        | undefined;
    } | null;
  } | null;
  market?: {
    phase?: string | null;
    et?: string | null;
    sydney?: string | null;
    trading_day_et?: string | null;
  } | null;
  /**
   * @maxItems 2000
   */
  dst?:
    | ({
        zone?: string | null;
        at_utc?: string | null;
        local_date?: string | null;
        from_offset?: string | null;
        to_offset?: string | null;
        days_away?: number | null;
      } | null)[]
    | null;
  overview?: {
    headline?: string | null;
    subline?: string | null;
    /**
     * @maxItems 2000
     */
    kpis?:
      | ({
          id?: string | null;
          label?: string | null;
          value?: string | null;
          unit?: string | null;
          state?: string | null;
          detail?: string | null;
        } | null)[]
      | null;
    /**
     * @maxItems 2000
     */
    needs_you?:
      | ({
          id?: string | null;
          rank?: number | null;
          title?: string | null;
          why?: string | null;
          blocks?: string | null;
          command?: string | null;
          when?: string | null;
          severity?: string | null;
          manual?: boolean | null;
        } | null)[]
      | null;
    /**
     * @maxItems 2000
     */
    gates?:
      | ({
          id?: string | null;
          name?: string | null;
          criteria?: string | null;
          status?: string | null;
          evidence?: string | null;
          next?: string | null;
          progress?: string | null;
        } | null)[]
      | null;
  } | null;
  research?: {
    /**
     * @maxItems 2000
     */
    scoreboard?:
      | ({
          label?: string | null;
          span?: string | null;
          verdict?: string | null;
          ref?: string | null;
          note?: string | null;
          n?: number | null;
          expectancy_r?: number | null;
          ci_low?: number | null;
          ci_high?: number | null;
          profit_factor?: number | null;
          dsr?: number | null;
          win_rate?: number | null;
          years_profitable?: string | null;
          error?: string | null;
        } | null)[]
      | null;
    cat01?: {
      accuracy_pct?: number | null;
      target_pct?: number | null;
      passed?: boolean | null;
      verdicts_done?: number | null;
      verdicts_total?: number | null;
    } | null;
    /**
     * @maxItems 2000
     */
    round3?:
      | ({
          id?: string | null;
          set?: string | null;
          hyp_status?: string | null;
          run?: boolean | null;
        } | null)[]
      | null;
    /**
     * @maxItems 2000
     */
    decisions?:
      | ({
          id?: string | null;
          date?: string | null;
          status?: string | null;
        } | null)[]
      | null;
    /**
     * @maxItems 2000
     */
    hypotheses?:
      | ({
          id?: string | null;
          status?: string | null;
          stale?: boolean | null;
        } | null)[]
      | null;
    /**
     * @maxItems 2000
     */
    active_strategies?: (string | null)[] | null;
    trials?: {
      used?: number | null;
      budget_if_round3?: number | null;
      in_force?: number | null;
      in_force_by?: string | null;
      proposed?: number | null;
      proposed_by?: string | null;
      g1_failed_at?: number | null;
    } | null;
    dec0010_status?: string | null;
    lessons_count?: number | null;
  } | null;
  spec?: {
    spec_id?: string | null;
    version?: string | null;
    status?: string | null;
    total?: number | null;
    by_status?: {
      [k: string]: number | null | undefined;
    } | null;
    by_level?: {
      [k: string]: number | null | undefined;
    } | null;
    /**
     * @maxItems 2000
     */
    by_area?:
      | ({
          area?: string | null;
          total?: number | null;
          implemented?: number | null;
          planned?: number | null;
          n_a?: number | null;
          needs_data?: number | null;
        } | null)[]
      | null;
    /**
     * @maxItems 2000
     */
    checklist?:
      | ({
          total?: number | null;
          implemented?: number | null;
          state?: string | null;
          /**
           * @maxItems 2000
           */
          reqs?: (string | null)[] | null;
        } | null)[]
      | null;
  } | null;
  platform?: {
    backlog_repo?: string | null;
    ci_repo?: string | null;
    /**
     * @maxItems 2000
     */
    milestones?:
      | ({
          key?: string | null;
          title?: string | null;
          state?: string | null;
          open?: number | null;
          closed?: number | null;
          p0_open?: number | null;
        } | null)[]
      | null;
    items_total?: number | null;
    items_done?: number | null;
    /**
     * @maxItems 2000
     */
    releases?:
      | ({
          tagName?: string | null;
          name?: string | null;
          publishedAt?: string | null;
          isLatest?: boolean | null;
        } | null)[]
      | null;
    /**
     * @maxItems 2000
     */
    runs?:
      | ({
          workflow?: string | null;
          conclusion?: string | null;
          created?: string | null;
          branch?: string | null;
        } | null)[]
      | null;
    required_checks?: boolean | null;
    /**
     * @maxItems 2000
     */
    roadmap?:
      | ({
          rank?: number | null;
          priority?: string | null;
          title?: string | null;
          why?: string | null;
          owner?: string | null;
        } | null)[]
      | null;
  } | null;
  ops?: {
    deployed?: {
      head?: string | null;
      branch?: string | null;
      committed?: string | null;
      modified?: number | null;
      untracked?: number | null;
      main?: string | null;
      behind?: number | null;
      ahead?: number | null;
    } | null;
    routine?: {
      date?: string | null;
      /**
       * @maxItems 2000
       */
      stages?:
        | ({
            stage?: string | null;
            as_of_et?: string | null;
            feed?: string | null;
            stats?: {
              [k: string]: number | null | undefined;
            } | null;
            counts?: {
              [k: string]: number | null | undefined;
            } | null;
            /**
             * @maxItems 2000
             */
            tier1?:
              | ({
                  symbol?: string | null;
                  score?: number | null;
                } | null)[]
              | null;
            /**
             * @maxItems 2000
             */
            tier2?: (string | null)[] | null;
            primary?: string | null;
            scan_failed?: boolean | null;
            error?: string | null;
          } | null)[]
        | null;
      near?: {
        total?: number | null;
        /**
         * @maxItems 2000
         */
        rows?:
          | ({
              symbol?: string | null;
              price?: number | null;
              reason?: string | null;
            } | null)[]
          | null;
      } | null;
      log?: {
        file?: string | null;
        exists?: boolean | null;
        bytes?: number | null;
        modified?: string | null;
        errors_count?: number | null;
        last_error?: string | null;
      } | null;
    } | null;
    paper?: {
      events?: {
        [k: string]: number | null | undefined;
      } | null;
      bad_lines?: number | null;
      armed_sessions?: number | null;
      last_armed?: string | null;
      trades?: number | null;
      total_r?: number | null;
      mean_r?: number | null;
      virtual?: {
        equity?: number | null;
        start?: number | null;
        latched?: boolean | null;
        latch_reason?: string | null;
      } | null;
      /**
       * @maxItems 2000
       */
      recent?:
        | ({
            ts?: string | null;
            event?: string | null;
            detail?: string | null;
          } | null)[]
        | null;
      g2?: {
        trades?: number | null;
        trades_needed?: number | null;
        sessions?: number | null;
        sessions_needed?: number | null;
        armed_sessions?: number | null;
        unchecked_sessions?: number | null;
        incident_free_streak?: number | null;
        incident_free_needed?: number | null;
        agreement_level?: string | null;
        agreement_days?: number | null;
        agreement_agree?: number | null;
      } | null;
      log?: {
        file?: string | null;
        exists?: boolean | null;
        bytes?: number | null;
        modified?: string | null;
        errors_count?: number | null;
        last_error?: string | null;
      } | null;
    } | null;
    forward?: {
      exists?: boolean | null;
      sessions?: number | null;
      first?: string | null;
      last?: string | null;
      errors?: number | null;
      bad_lines?: number | null;
      /**
       * @maxItems 2000
       */
      strategies?:
        | ({
            strategy?: string | null;
            n?: number | null;
            mean_r?: number | null;
            total_r?: number | null;
          } | null)[]
        | null;
      latest_scorecard?: string | null;
      /**
       * @maxItems 2000
       */
      books?:
        | ({
            strategy?: string | null;
            hyp?: string | null;
            sessions?: number | null;
            errors?: number | null;
            first?: string | null;
            last?: string | null;
            trades?: number | null;
            total_r?: number | null;
            max_dd_r?: number | null;
            last_trade?: string | null;
            risk_usd?: number | null;
            nominal_usd?: number | null;
            signals?: number | null;
            refused?: number | null;
            shadow_resolved?: number | null;
          } | null)[]
        | null;
      funnel?: {
        session?: string | null;
        pool?: {
          [k: string]: number | null | undefined;
        } | null;
        counts?: {
          [k: string]: number | null | undefined;
        } | null;
      } | null;
      log?: {
        file?: string | null;
        exists?: boolean | null;
        bytes?: number | null;
        modified?: string | null;
        errors_count?: number | null;
        last_error?: string | null;
      } | null;
    } | null;
    host?: {
      /**
       * @maxItems 2000
       */
      jobs?:
        | ({
            label?: string | null;
            local_time?: string | null;
            name?: string | null;
            loaded?: boolean | null;
            running?: boolean | null;
            last_exit?: number | null;
          } | null)[]
        | null;
      disk_free_gb?: number | null;
      disk_total_gb?: number | null;
      disk_floor_gb?: number | null;
      disk_target_gb?: number | null;
      swap_warn_pct?: number | null;
      swap?: {
        total_gb?: number | null;
        used_gb?: number | null;
        free_gb?: number | null;
        used_pct?: number | null;
      } | null;
      /**
       * @maxItems 2000
       */
      wake_coverage?:
        | ({
            needed?: string | null;
            covered?: boolean | null;
          } | null)[]
        | null;
      /**
       * @maxItems 2000
       */
      schedule?:
        | ({
            job?: string | null;
            local?: string | null;
            et?: string | null;
            et_date?: string | null;
            session?: boolean | null;
            ok?: boolean | null;
            must_start_before_et?: string | null;
          } | null)[]
        | null;
    } | null;
    account?: {
      equity?: number | null;
      last_equity?: number | null;
      cash?: number | null;
      buying_power?: number | null;
      daytrade_count?: number | null;
      pattern_day_trader?: boolean | null;
      status?: string | null;
      trading_blocked?: boolean | null;
      market_is_open?: boolean | null;
      next_open?: string | null;
      next_close?: string | null;
      paper?: boolean | null;
      /**
       * @maxItems 2000
       */
      positions?:
        | ({
            symbol?: string | null;
            qty?: number | null;
            market_value?: number | null;
            unrealized_pl?: number | null;
            in_mandate?: boolean | null;
            legacy?: boolean | null;
          } | null)[]
        | null;
    } | null;
  } | null;
  jobs?: {
    last?: {
      [k: string]:
        | {
            status?: string | null;
            exit?: number | null;
            started?: string | null;
            ended?: string | null;
            sha?: string | null;
            detail?: string | null;
          }
        | null
        | undefined;
    } | null;
    /**
     * @maxItems 2000
     */
    runs?:
      | ({
          job?: string | null;
          status?: string | null;
          exit?: number | null;
          started?: string | null;
          ended?: string | null;
          sha?: string | null;
        } | null)[]
      | null;
  } | null;
  alerts?: {
    /**
     * @maxItems 2000
     */
    firing?:
      | ({
          key?: string | null;
          since?: string | null;
          title?: string | null;
        } | null)[]
      | null;
    /**
     * @maxItems 2000
     */
    history?:
      | ({
          at?: string | null;
          key?: string | null;
          event?: "fired" | "resolved" | null;
          title?: string | null;
          priority?: number | null;
        } | null)[]
      | null;
  } | null;
  kill?: {
    on?: boolean | null;
    since?: string | null;
    reason?: string | null;
  } | null;
  deploy?: {
    to?: string | null;
    rollback_tag?: string | null;
    at?: string | null;
    smoke_ok?: boolean | null;
  } | null;
  /**
   * @maxItems 2000
   */
  preflight?:
    | ({
        name?: string | null;
        ok?: boolean | null;
        detail?: string | null;
      } | null)[]
    | null;
  /**
   * @maxItems 2000
   */
  expected_windows?:
    | ({
        session?: string | null;
        start?: string | null;
        end?: string | null;
      } | null)[]
    | null;
  series?: {
    /**
     * @maxItems 2000
     */
    forward?:
      | ({
          strategy?: string | null;
          session?: string | null;
          n?: number | null;
          cum_r?: number | null;
        } | null)[]
      | null;
    /**
     * @maxItems 2000
     */
    paper?:
      | ({
          date?: string | null;
          equity?: number | null;
          cum_r?: number | null;
          trades?: number | null;
        } | null)[]
      | null;
  } | null;
  history?: {
    /**
     * @maxItems 2000
     */
    timeline?:
      | ({
          date?: string | null;
          event?: string | null;
        } | null)[]
      | null;
    legacy?: {
      total?: number | null;
      orders_placed?: number | null;
      first?: string | null;
      last?: string | null;
      by_outcome?: {
        [k: string]: number | null | undefined;
      } | null;
    } | null;
  } | null;
  risk?: {
    /**
     * @maxItems 2000
     */
    limits?:
      | ({
          id?: string | null;
          label?: string | null;
          limit?: string | null;
          used?: string | null;
          used_pct?: number | null;
          state?: "ok" | "warn" | "at_limit" | "n/a" | null;
          source?: string | null;
          source_sha?: string | null;
        } | null)[]
      | null;
    controls?: {
      kill?: boolean | null;
      latched?: boolean | null;
      latch_reason?: string | null;
      latch_resets?: number | null;
      last_reset?: string | null;
      entries_allowed?: boolean | null;
    } | null;
    used_today?: {
      date?: string | null;
      day_pnl_pct?: number | null;
      week_pnl_pct?: number | null;
      drawdown_pct?: number | null;
      entries?: number | null;
    } | null;
    sources?: {
      [k: string]: string | null | undefined;
    } | null;
  } | null;
  perf?: {
    stats?: {
      n?: number | null;
      excluded_estimated?: number | null;
      win_rate?: number | null;
      avg_win_r?: number | null;
      avg_loss_r?: number | null;
      expectancy_r?: number | null;
      total_r?: number | null;
      sample_ok?: boolean | null;
      ci_low?: number | null;
      ci_high?: number | null;
      profit_factor?: number | null;
      pf_no_losses?: boolean | null;
      sharpe?: number | null;
    } | null;
    sessions?: number | null;
    min_trades?: number | null;
    min_sessions?: number | null;
    max_dd_pct?: number | null;
    max_dd_r?: number | null;
    /**
     * @maxItems 2000
     */
    curve?:
      | ({
          date?: string | null;
          equity_pct?: number | null;
          cum_r?: number | null;
          dd_pct?: number | null;
          dd_r?: number | null;
        } | null)[]
      | null;
    /**
     * @maxItems 2000
     */
    histogram?:
      | ({
          bin?: string | null;
          count?: number | null;
        } | null)[]
      | null;
    band?: {
      available?: boolean | null;
      reason?: string | null;
    } | null;
  } | null;
  /**
   * @maxItems 2000
   */
  blotter?:
    | ({
        date?: string | null;
        symbol?: string | null;
        qty?: number | null;
        entry?: number | null;
        exit?: number | null;
        stop?: number | null;
        r?: number | null;
        reason?: string | null;
        origin?: string | null;
        estimated?: boolean | null;
        booked?: boolean | null;
      } | null)[]
    | null;
  sla?: {
    /**
     * @maxItems 2000
     */
    days?: (string | null)[] | null;
    /**
     * @maxItems 2000
     */
    cells?:
      | ({
          job?: string | null;
          date?: string | null;
          status?: "ok" | "refused" | "failed" | "partial" | "missed" | "none" | "n/a" | null;
          runs?: number | null;
        } | null)[]
      | null;
    /**
     * @maxItems 2000
     */
    summary?:
      | ({
          job?: string | null;
          expected?: number | null;
          ok?: number | null;
          refused?: number | null;
          failed?: number | null;
          missed?: number | null;
          ok_pct?: number | null;
        } | null)[]
      | null;
  } | null;
  digest?: {
    since?: string | null;
    /**
     * @maxItems 2000
     */
    items?:
      | ({
          key?: string | null;
          label?: string | null;
          prev?: string | null;
          now?: string | null;
          changed?: boolean | null;
        } | null)[]
      | null;
  } | null;
  audit?: {
    chain_ok?: boolean | null;
    chain_bad_seq?: number | null;
    rows?: number | null;
    bad_lines?: number | null;
    /**
     * @maxItems 2000
     */
    events?:
      | ({
          at?: string | null;
          kind?: string | null;
          source?: string | null;
          detail?: string | null;
        } | null)[]
      | null;
  } | null;
  today?: {
    session?: string | null;
    outcome?: string | null;
    ended?: boolean | null;
    armed?: {
      at?: string | null;
      kill?: boolean | null;
      entries_off?: number | null;
    } | null;
    /**
     * @maxItems 2000
     */
    signals?:
      | ({
          at?: string | null;
          trigger?: number | null;
          stop?: number | null;
          blockers?: string | null;
          acted?: boolean | null;
        } | null)[]
      | null;
    position?: {
      symbol?: string | null;
      state?: string | null;
      qty?: number | null;
      entry?: number | null;
      entry_at?: string | null;
      trigger?: number | null;
      stop?: number | null;
      target?: number | null;
    } | null;
    pnl?: {
      today?: number | null;
      week?: number | null;
      month?: number | null;
      total?: number | null;
      today_r?: number | null;
      week_r?: number | null;
      month_r?: number | null;
      total_r?: number | null;
      today_trades?: number | null;
      week_trades?: number | null;
      month_trades?: number | null;
      equity?: number | null;
      start?: number | null;
      return_pct?: number | null;
      trades?: number | null;
      wins?: number | null;
      losses?: number | null;
      win_rate?: number | null;
      avg_win?: number | null;
      avg_loss?: number | null;
      profit_factor?: number | null;
      best?: number | null;
      worst?: number | null;
      max_dd?: number | null;
    } | null;
    /**
     * @maxItems 2000
     */
    trades?:
      | ({
          session?: string | null;
          symbol?: string | null;
          qty?: number | null;
          entry?: number | null;
          entry_at?: string | null;
          exit?: number | null;
          exit_at?: string | null;
          stop?: number | null;
          target?: number | null;
          pnl?: number | null;
          r?: number | null;
          reason?: string | null;
          held_min?: number | null;
          estimated?: boolean | null;
          origin?: string | null;
        } | null)[]
      | null;
    /**
     * @maxItems 2000
     */
    days?:
      | ({
          date?: string | null;
          pnl?: number | null;
          r?: number | null;
          trades?: number | null;
        } | null)[]
      | null;
  } | null;
}
