// Generated by scripts/gen_thresholds_ts.py from src/wt/ops/thresholds.py. Do not edit by hand.

export const DISK_FLOOR_GB = 3.0;
export const DISK_TARGET_GB = 15.0;
export const SWAP_WARN_PCT = 85.0;
